//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class ADMIN_SummaryReportToken
    {
        public string period { get; set; }
        public long users { get; set; }
        public decimal total { get; set; }
        public long courses { get; set; }
        public long authors { get; set; }
    }
}
