//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class ADMIN_SaleSummaryToken
    {
        public decimal total { get; set; }
        public Nullable<int> SellerUserId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal refund { get; set; }
        public decimal fee { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public string PaypalEmail { get; set; }
        public Nullable<int> PayoutAddressID { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<short> StateId { get; set; }
        public string StateName { get; set; }
        public string AddressFirstName { get; set; }
        public string AddressLastName { get; set; }
        public string CityName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public decimal refundFee { get; set; }
    }
}
