//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class ADMIN_VideoStatsToken
    {
        public System.DateTime period { get; set; }
        public int total { get; set; }
        public int used { get; set; }
    }
}
