//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiSessions
    {
        public int id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public string Token { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
