//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PluginInstallationStores
    {
        public int RowId { get; set; }
        public int StoreId { get; set; }
        public int InstallationId { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime AddOn { get; set; }
    
        public virtual APP_PluginInstallations APP_PluginInstallations { get; set; }
        public virtual WebStores WebStores { get; set; }
    }
}
