//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PluginInstallations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APP_PluginInstallations()
        {
            this.APP_PluginInstallationStores = new HashSet<APP_PluginInstallationStores>();
        }
    
        public int InstallationId { get; set; }
        public byte TypeId { get; set; }
        public string UId { get; set; }
        public string Domain { get; set; }
        public Nullable<decimal> Version { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_PluginInstallationStores> APP_PluginInstallationStores { get; set; }
        public virtual Users Users { get; set; }
    }
}
