//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CurrencyLib
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_CurrencyLib()
        {
            this.BILL_ItemsPriceList = new HashSet<BILL_ItemsPriceList>();
            this.WebStores = new HashSet<WebStores>();
            this.PO_UserPayoutStatments = new HashSet<PO_UserPayoutStatments>();
        }
    
        public short CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string ISO { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string Symbol { get; set; }
        public Nullable<short> OrderIndex { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool KeepDecimal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_ItemsPriceList> BILL_ItemsPriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStores> WebStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_UserPayoutStatments> PO_UserPayoutStatments { get; set; }
    }
}
