//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.CourseCategories = new HashSet<CourseCategories>();
            this.WebStoreCategories = new HashSet<WebStoreCategories>();
            this.CRS_BundleCategories = new HashSet<CRS_BundleCategories>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryUrlName { get; set; }
        public string CategoryDescription { get; set; }
        public int IsOnHomePage { get; set; }
        public int Ordinal { get; set; }
        public string BannerImageUrl { get; set; }
        public string Keywords { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCategories> CourseCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStoreCategories> WebStoreCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRS_BundleCategories> CRS_BundleCategories { get; set; }
    }
}
