//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERT_CertificateLib
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CERT_CertificateLib()
        {
            this.CERT_StudentCertificates = new HashSet<CERT_StudentCertificates>();
        }
    
        public int CertificateId { get; set; }
        public int CourseId { get; set; }
        public byte TemplateId { get; set; }
        public string Title { get; set; }
        public string CourseName { get; set; }
        public string SitgnatureUrl { get; set; }
        public string PresentedBy { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual CERT_TemplatesLOV CERT_TemplatesLOV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERT_StudentCertificates> CERT_StudentCertificates { get; set; }
    }
}
