//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERT_StudentCertificates
    {
        public System.Guid StudentCertificateId { get; set; }
        public int CertificateId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public byte TemplateId { get; set; }
        public string Title { get; set; }
        public string CourseName { get; set; }
        public string SitgnatureUrl { get; set; }
        public string PresentedBy { get; set; }
        public string Description { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual CERT_CertificateLib CERT_CertificateLib { get; set; }
        public virtual Users Users { get; set; }
    }
}
