//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterLinks
    {
        public int Id { get; set; }
        public int CourseChapterId { get; set; }
        public string LinkText { get; set; }
        public int LinkType { get; set; }
        public string LinkHref { get; set; }
        public int Ordinal { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual CourseChapters CourseChapters { get; set; }
    }
}
