//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterVideos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChapterVideos()
        {
            this.FB_PostInterface = new HashSet<FB_PostInterface>();
        }
    
        public int Id { get; set; }
        public int CourseChapterId { get; set; }
        public string VideoTitle { get; set; }
        public string VideoSummary { get; set; }
        public string VideoSupplierIdentifier { get; set; }
        public int IsOpen { get; set; }
        public int Ordinal { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<long> FbObjectId { get; set; }
    
        public virtual CourseChapters CourseChapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_PostInterface> FB_PostInterface { get; set; }
    }
}
