//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class CHIMP_ItemSubscribers
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public System.DateTime AddOn { get; set; }
        public byte StatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
