//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIMP_ListSegments
    {
        public int SegmentId { get; set; }
        public int ListId { get; set; }
        public string Uid { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> SubscribersLastUpdate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public byte SegmentTypeId { get; set; }
        public string Name { get; set; }
        public int TotalSubscribers { get; set; }
    
        public virtual CHIMP_UserLists CHIMP_UserLists { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
