//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIMP_UserLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHIMP_UserLists()
        {
            this.CHIMP_ListSegments = new HashSet<CHIMP_ListSegments>();
        }
    
        public int ListId { get; set; }
        public int UserId { get; set; }
        public string ApiKey { get; set; }
        public string Uid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> SubscribersLastUpdate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int TotalSubscribers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIMP_ListSegments> CHIMP_ListSegments { get; set; }
        public virtual Users Users { get; set; }
    }
}
