//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupons()
        {
            this.CouponInstances = new HashSet<CouponInstances>();
        }
    
        public int Id { get; set; }
        public string CouponName { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerUserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public byte CouponTypeId { get; set; }
        public Nullable<double> CouponTypeAmount { get; set; }
        public bool AutoGenerate { get; set; }
        public Nullable<byte> SubscriptionMonths { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string salesforce_id { get; set; }
        public string salesforce_checksum { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponInstances> CouponInstances { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
