//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.CHIMP_ListSegments = new HashSet<CHIMP_ListSegments>();
            this.Coupons = new HashSet<Coupons>();
            this.CourseCategories = new HashSet<CourseCategories>();
            this.CourseChapters = new HashSet<CourseChapters>();
            this.CourseLinks = new HashSet<CourseLinks>();
            this.CRS_BundleCourses = new HashSet<CRS_BundleCourses>();
            this.DSC_Followers = new HashSet<DSC_Followers>();
            this.DSC_Messages = new HashSet<DSC_Messages>();
            this.FB_PostInterface = new HashSet<FB_PostInterface>();
            this.PAYPAL_PaymentRequests = new HashSet<PAYPAL_PaymentRequests>();
            this.SALE_OrderLines = new HashSet<SALE_OrderLines>();
            this.USER_Courses = new HashSet<USER_Courses>();
            this.USER_CourseWatchState = new HashSet<USER_CourseWatchState>();
            this.UserCourseReviews = new HashSet<UserCourseReviews>();
            this.UserSessionsEventLogs = new HashSet<UserSessionsEventLogs>();
            this.WebStoreItems = new HashSet<WebStoreItems>();
            this.CRS_Assets = new HashSet<CRS_Assets>();
            this.QZ_CourseQuizzes = new HashSet<QZ_CourseQuizzes>();
            this.CERT_CertificateLib = new HashSet<CERT_CertificateLib>();
        }
    
        public int Id { get; set; }
        public System.Guid uid { get; set; }
        public string CourseName { get; set; }
        public string CourseUrlName { get; set; }
        public int AuthorUserId { get; set; }
        public decimal AffiliateCommission { get; set; }
        public string SmallImage { get; set; }
        public string Description { get; set; }
        public string OverviewVideoIdentifier { get; set; }
        public Nullable<int> Rating { get; set; }
        public string MetaTags { get; set; }
        public Nullable<int> ClassRoomId { get; set; }
        public Nullable<long> FbObjectId { get; set; }
        public bool FbObjectPublished { get; set; }
        public bool IsFreeCourse { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public short StatusId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool DisplayOtherLearnersTab { get; set; }
        public Nullable<System.Guid> ProvisionUid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIMP_ListSegments> CHIMP_ListSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupons> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCategories> CourseCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseChapters> CourseChapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseLinks> CourseLinks { get; set; }
        public virtual StatusLOV StatusLOV { get; set; }
        public virtual DSC_ClassRoom DSC_ClassRoom { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRS_BundleCourses> CRS_BundleCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Followers> DSC_Followers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Messages> DSC_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_PostInterface> FB_PostInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYPAL_PaymentRequests> PAYPAL_PaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_OrderLines> SALE_OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Courses> USER_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_CourseWatchState> USER_CourseWatchState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCourseReviews> UserCourseReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSessionsEventLogs> UserSessionsEventLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStoreItems> WebStoreItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRS_Assets> CRS_Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QZ_CourseQuizzes> QZ_CourseQuizzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERT_CertificateLib> CERT_CertificateLib { get; set; }
    }
}
