//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseChapters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseChapters()
        {
            this.ChapterLinks = new HashSet<ChapterLinks>();
            this.ChapterVideos = new HashSet<ChapterVideos>();
            this.USER_VideoStats = new HashSet<USER_VideoStats>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string ChapterName { get; set; }
        public string ChapterDescriptionHTML { get; set; }
        public int ChapterOrdinal { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChapterLinks> ChapterLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChapterVideos> ChapterVideos { get; set; }
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_VideoStats> USER_VideoStats { get; set; }
    }
}
