//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class CRS_CouponToken
    {
        public int Id { get; set; }
        public string CouponName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CourseId { get; set; }
        public byte CouponTypeId { get; set; }
        public Nullable<double> CouponTypeAmount { get; set; }
        public bool AutoGenerate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsDeleteAllowed { get; set; }
        public Nullable<int> BundleId { get; set; }
        public Nullable<byte> SubscriptionMonths { get; set; }
        public Nullable<int> UsageLimit { get; set; }
        public Nullable<int> ActualUsage { get; set; }
        public string CourseName { get; set; }
        public string BundleName { get; set; }
    }
}
