//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRS_CourseChangeLog
    {
        public long RowId { get; set; }
        public System.Guid Uid { get; set; }
        public System.DateTime LastUpdateOn { get; set; }
    }
}
