//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class CRS_BundleCourseToken
    {
        public int BundleCourseId { get; set; }
        public int BundleId { get; set; }
        public int CourseId { get; set; }
        public bool IsActive { get; set; }
        public short OrderIndex { get; set; }
        public string CourseName { get; set; }
        public string CourseUrlName { get; set; }
        public string CourseDescription { get; set; }
        public string SmallImage { get; set; }
        public string OverviewVideoIdentifier { get; set; }
        public short StatusId { get; set; }
        public int AuthorUserId { get; set; }
        public string AuthorNickName { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
    }
}
