//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class CRS_ReviewLearnerMessageToken
    {
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewText { get; set; }
        public int ReviewWriterId { get; set; }
        public string ReviewWriterNickname { get; set; }
        public string ReviewWriterFirstName { get; set; }
        public string ReviewWriterLastName { get; set; }
        public string AuthorNickname { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string AuthorFacebookID { get; set; }
        public int AuthorUserId { get; set; }
        public string LearnerFacebookID { get; set; }
        public string CourseName { get; set; }
        public string CourseUrlName { get; set; }
        public int CourseId { get; set; }
        public int LearnerUserId { get; set; }
        public string LearnerEmail { get; set; }
        public string LearnerNickname { get; set; }
        public string LearnerFirstName { get; set; }
        public string LearnerLastName { get; set; }
        public string CourseThumbUrl { get; set; }
        public string CourseDescription { get; set; }
    }
}
