//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRS_BundleCategories
    {
        public int Id { get; set; }
        public int BundleId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
    }
}
