//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRS_BundleCourses
    {
        public int BundleCourseId { get; set; }
        public int BundleId { get; set; }
        public int CourseId { get; set; }
        public bool IsActive { get; set; }
        public short OrderIndex { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
