//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class CRS_AvailableCourseToken
    {
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string SmallImage { get; set; }
        public short StatusId { get; set; }
    }
}
