//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRS_Assets
    {
        public int AssetId { get; set; }
        public int CourseId { get; set; }
        public byte AssetTypeId { get; set; }
        public string AssetUrl { get; set; }
        public Nullable<long> BcIdentifier { get; set; }
        public string RefId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short OrderIndex { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
