//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DB_AuthorSalesStatsToken
    {
        public int UserId { get; set; }
        public short CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public decimal AuthorTotalOnetimeSales { get; set; }
        public int AuthorTotalOnetimeQty { get; set; }
        public decimal AuthorTotalSubscriptionSales { get; set; }
        public int AuthorTotalSubscriptionQty { get; set; }
        public decimal AuthorTotalRentalSales { get; set; }
        public int AuthorTotalRentalQty { get; set; }
        public int AffiliateTotalQty { get; set; }
        public decimal TotalRefund { get; set; }
        public int TotalRefundQty { get; set; }
        public decimal TotalCancelled { get; set; }
        public int TotalCancelledQty { get; set; }
        public decimal TotalCouponValue { get; set; }
        public int TotalCouponQty { get; set; }
        public decimal ByAffiliateTotalSales { get; set; }
        public decimal AffiliateTotalSales { get; set; }
        public int ByAffiliateTotalQty { get; set; }
    }
}
