//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DB_AuthorEventStatsToken
    {
        public Nullable<System.DateTime> LastCoursePublish { get; set; }
        public Nullable<System.DateTime> LastBundlePublish { get; set; }
        public Nullable<System.DateTime> LastChaperCreated { get; set; }
        public Nullable<System.DateTime> LastFbStoreCreated { get; set; }
        public Nullable<System.DateTime> LastStoreCreated { get; set; }
    }
}
