//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DROP_JobToken
    {
        public int JobId { get; set; }
        public int UserId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public Nullable<int> CourseId { get; set; }
        public byte StatusId { get; set; }
        public string Error { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CourseName { get; set; }
        public string StatusCode { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
