//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DROP_JobFileToken
    {
        public int FileId { get; set; }
        public int JobId { get; set; }
        public string Type { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string ChapterName { get; set; }
        public Nullable<long> BcIdentifier { get; set; }
        public string SavedToPath { get; set; }
        public bool IsContentCreated { get; set; }
        public string Status { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> DownloadOn { get; set; }
        public Nullable<System.DateTime> UploadOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<System.DateTime> SyncOn { get; set; }
        public Nullable<int> ChapterId { get; set; }
    }
}
