//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_Hashtags
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSC_Hashtags()
        {
            this.DSC_MessageHashtags = new HashSet<DSC_MessageHashtags>();
        }
    
        public long HashtagId { get; set; }
        public string HashTag { get; set; }
        public System.DateTime AddOn { get; set; }
        public int CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_MessageHashtags> DSC_MessageHashtags { get; set; }
        public virtual Users Users { get; set; }
    }
}
