//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSC_Messages()
        {
            this.DSC_Messages1 = new HashSet<DSC_Messages>();
            this.DSC_MessageUsers = new HashSet<DSC_MessageUsers>();
            this.UserNotifications = new HashSet<UserNotifications>();
            this.DSC_MessageHashtags = new HashSet<DSC_MessageHashtags>();
        }
    
        public long MessageId { get; set; }
        public System.Guid Uid { get; set; }
        public int ClassRoomId { get; set; }
        public int CourseId { get; set; }
        public short MessageKindId { get; set; }
        public Nullable<long> ParentMessageId { get; set; }
        public string Text { get; set; }
        public string HtmlMessage { get; set; }
        public int HtmlVersion { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string HtmlEmailMessage { get; set; }
    
        public virtual DSC_ClassRoom DSC_ClassRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Messages> DSC_Messages1 { get; set; }
        public virtual DSC_Messages DSC_Messages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_MessageUsers> DSC_MessageUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotifications> UserNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_MessageHashtags> DSC_MessageHashtags { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
