//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DSC_AuhtorRoomToken
    {
        public int ClassRoomId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime AddOn { get; set; }
        public int Cnt { get; set; }
    }
}
