//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_Followers
    {
        public long RowId { get; set; }
        public int FollowerId { get; set; }
        public int ClassRoomId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime AddOn { get; set; }
    
        public virtual DSC_ClassRoom DSC_ClassRoom { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
