//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class DSC_NotificationsFbToken
    {
        public int UserId { get; set; }
        public string FacebookID { get; set; }
        public bool FbPostRequired { get; set; }
        public Nullable<System.DateTime> FbPostSendOn { get; set; }
        public System.Guid Uid { get; set; }
        public long MessageId { get; set; }
        public string MessageText { get; set; }
        public long NotificationId { get; set; }
        public string PosterNickname { get; set; }
        public string PosterFirstName { get; set; }
        public string PosterLastName { get; set; }
        public System.DateTime AddOn { get; set; }
        public string CourseName { get; set; }
        public string CourseUrlName { get; set; }
        public string CourseThumbUrl { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> AuthorUserId { get; set; }
        public string AuthorNickname { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
    }
}
