//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class EMAIL_NotificationMessageToken
    {
        public long NotificationId { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long MessageId { get; set; }
        public string Text { get; set; }
        public int PosterId { get; set; }
        public string PosterNickname { get; set; }
        public string PosterFirstName { get; set; }
        public string PosterLastName { get; set; }
        public System.DateTime AddOn { get; set; }
        public string HtmlEmailMessage { get; set; }
    }
}
