//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_Messages
    {
        public long EmailId { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public string Subject { get; set; }
        public string MessageFrom { get; set; }
        public string ToEmail { get; set; }
        public string ToName { get; set; }
        public string MessageBoby { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public string Status { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public int UserId { get; set; }
    
        public virtual UserNotifications UserNotifications { get; set; }
        public virtual Users Users { get; set; }
    }
}
