//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_LearnerPeriodStatsToken
    {
        public int TotalActiveLearners { get; set; }
        public int TotalVideosWatched { get; set; }
        public int TotalCoursesWatched { get; set; }
        public decimal AvgLearnerLogin { get; set; }
        public int TotalVideoPreveiwWatched { get; set; }
        public int TotalCoursePreviewEntered { get; set; }
        public int TotalPurchasePageEntered { get; set; }
        public int TotalPurchaseComplete { get; set; }
    }
}
