//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_OwnerEventDailyStatsToken
    {
        public Nullable<System.DateTime> EventDate { get; set; }
        public byte OwnerTypeId { get; set; }
        public int cnt { get; set; }
    }
}
