//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_HostEventToken
    {
        public string period { get; set; }
        public string HostName { get; set; }
        public int REGISTRATION_SUCCESS { get; set; }
        public int STORE_VIEW { get; set; }
        public int PURCHASE_COMPLETE { get; set; }
        public int COURSE_PREVIEW_ENTER { get; set; }
        public int COURSE_VIEWER_ENTER { get; set; }
        public int CHECKOUT_REGISTER { get; set; }
        public int BUY_PAGE_ENTERED { get; set; }
    }
}
