//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_AuthorTotalStatsToken
    {
        public decimal AverageCourseChapters { get; set; }
        public decimal AverageCoursesPerAuthor { get; set; }
        public decimal AverageBundlesPerAuthor { get; set; }
        public int TotalFreeCourses { get; set; }
        public decimal AverageFreeCoursesPerAuthor { get; set; }
    }
}
