//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_PeriodSalesStatsToken
    {
        public int total_onetime_qty { get; set; }
        public int total_subscription_qty { get; set; }
        public int total_rental_qty { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public int total_free_qty { get; set; }
        public int total_mbg_qty { get; set; }
    }
}
