//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_EventAgg
    {
        public long FactId { get; set; }
        public int EventCount { get; set; }
        public short EventTypeID { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> AuthorId { get; set; }
    
        public virtual WebStores WebStores { get; set; }
        public virtual Users Users { get; set; }
    }
}
