//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_DailyTotals
    {
        public int FactId { get; set; }
        public int TotalItems { get; set; }
        public int TotalPublished { get; set; }
        public int Attached2Stores { get; set; }
        public int Attached2WixStores { get; set; }
        public int TotalUsers { get; set; }
        public int TotalAuthors { get; set; }
        public int TotalLearners { get; set; }
        public System.DateTime FactDate { get; set; }
        public int ItemsPurchased { get; set; }
        public int FreeItemsPurchased { get; set; }
        public int StoresCreated { get; set; }
        public int WixStoresCreated { get; set; }
    }
}
