//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_PlatformStats
    {
        public byte RegistrationTypeId { get; set; }
        public int NewAuthors { get; set; }
        public int TotalAuhtors { get; set; }
        public int NewItems { get; set; }
        public int TotalItems { get; set; }
        public int NewStores { get; set; }
        public int TotalStores { get; set; }
        public int NewLearners { get; set; }
        public int TotalLearners { get; set; }
        public int NewSales { get; set; }
        public int TotalSales { get; set; }
        public System.DateTime FactDate { get; set; }
        public int TotalPlatformNew { get; set; }
    }
}
