//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_DailyStats
    {
        public int FactId { get; set; }
        public int ItemsCreated { get; set; }
        public int ItemsPublished { get; set; }
        public int UsersCreated { get; set; }
        public int UserLogins { get; set; }
        public int ItemsPurchased { get; set; }
        public int StoresCreated { get; set; }
        public System.DateTime FactDate { get; set; }
        public int WixUsersCreated { get; set; }
        public int AuthorLogins { get; set; }
        public int ReturnUsersLogins { get; set; }
        public int FreeItemsPurchased { get; set; }
        public int WixStoresCreated { get; set; }
    }
}
