//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_NewPeriodTotalsToken
    {
        public System.DateTime FactDate { get; set; }
        public int NewAuthors { get; set; }
        public int NewCourses { get; set; }
        public int NewBundles { get; set; }
        public int NewStores { get; set; }
        public int NewLearners { get; set; }
        public int NumOfOneTimeSales { get; set; }
        public int NumOfSubscriptionSales { get; set; }
        public int NumOfRentalSales { get; set; }
        public int NumOfFreeSales { get; set; }
        public int NewMailchimpLists { get; set; }
        public int NewMBGJoined { get; set; }
        public int MBGCancelled { get; set; }
    }
}
