//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_TotalsToken
    {
        public Nullable<int> TotalAuthors { get; set; }
        public Nullable<int> TotalLearners { get; set; }
        public Nullable<int> TotalCourses { get; set; }
        public Nullable<int> TotalBundles { get; set; }
        public Nullable<int> TotalStores { get; set; }
        public Nullable<int> TotalVideos { get; set; }
        public Nullable<int> TotalAttached2ActiveCourses { get; set; }
        public Nullable<int> UnattachedVideos { get; set; }
        public Nullable<int> VideoPreviews { get; set; }
    }
}
