//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_DASH_PeriodSalesTotalsToken
    {
        public Nullable<decimal> total_sales { get; set; }
        public Nullable<int> total_payment_qty { get; set; }
        public Nullable<decimal> total_onetime_sales { get; set; }
        public Nullable<int> total_onetime_qty { get; set; }
        public Nullable<decimal> total_subscription_sales { get; set; }
        public Nullable<int> total_subscription_qty { get; set; }
        public Nullable<decimal> total_rental_sales { get; set; }
        public Nullable<int> total_rental_qty { get; set; }
        public short CurrencyId { get; set; }
    }
}
