//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class FACT_AbandonHostToken
    {
        public string HostName { get; set; }
        public Nullable<System.DateTime> LastEventDate { get; set; }
        public Nullable<System.DateTime> FirstEventDate { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public int WebStoreId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TotalEvents { get; set; }
        public Nullable<int> PreviewCount { get; set; }
        public int TotalCourses { get; set; }
    }
}
