//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_PostInterface
    {
        public long PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> FbUid { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public string FbUserName { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string LinkedName { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Error { get; set; }
        public string FbPostId { get; set; }
        public bool IsAppPagePost { get; set; }
        public Nullable<byte> ActionId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Status { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> PostOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> ChapterVideoId { get; set; }
    
        public virtual UserNotifications UserNotifications { get; set; }
        public virtual ChapterVideos ChapterVideos { get; set; }
        public virtual Users Users { get; set; }
        public virtual FB_ActionsLOV FB_ActionsLOV { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
