//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class LOG_FbPostInterfaceToken
    {
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureURL { get; set; }
        public string FacebookID { get; set; }
        public long PostId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string LinkedName { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Error { get; set; }
        public string FbPostId { get; set; }
        public string Status { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> PostOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
