//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class LOG_EmailInterfaceToken
    {
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureURL { get; set; }
        public string FacebookID { get; set; }
        public long EmailId { get; set; }
        public int UserId { get; set; }
        public string Subject { get; set; }
        public string ToEmail { get; set; }
        public string ToName { get; set; }
        public string MessageBoby { get; set; }
        public string Status { get; set; }
        public string Error { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
    }
}
