//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class LOG_FileInterfaceToken
    {
        public int FileId { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureURL { get; set; }
        public string FacebookID { get; set; }
        public string FilePath { get; set; }
        public string ETag { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> BcIdentifier { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public string Status { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
