//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class LRNR_ItemToken
    {
        public int Id { get; set; }
        public System.Guid Uid { get; set; }
        public int AuthorUserId { get; set; }
        public string AuthorNickname { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string CourseName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MonthlySubscriptionPrice { get; set; }
        public System.DateTime Created { get; set; }
        public string SmallImage { get; set; }
        public string OverviewVideoIdentifier { get; set; }
        public int ReviewCount { get; set; }
        public int Rating { get; set; }
        public int NumSubscribers { get; set; }
        public int UserId { get; set; }
        public bool IsFreeCourse { get; set; }
        public string CourseUrlName { get; set; }
    }
}
