//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYPAL_IpnLogs
    {
        public int RowId { get; set; }
        public string recurring_payment_id { get; set; }
        public string txn_type { get; set; }
        public string txn_id { get; set; }
        public string parent_txn_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> mc_gross { get; set; }
        public Nullable<decimal> mc_fee { get; set; }
        public string response { get; set; }
        public System.DateTime AddOn { get; set; }
        public string initial_payment_txn_id { get; set; }
        public Nullable<decimal> initial_payment_amount { get; set; }
    }
}
