//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYPAL_PaymentRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYPAL_PaymentRequests()
        {
            this.PAYPAL_PaymentRequests1 = new HashSet<PAYPAL_PaymentRequests>();
            this.SALE_Transactions = new HashSet<SALE_Transactions>();
        }
    
        public System.Guid RequestId { get; set; }
        public int Sid { get; set; }
        public byte PaymentMethodId { get; set; }
        public string CreatePaymentId { get; set; }
        public string ExecutionPaymentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string Error { get; set; }
        public System.DateTime AddOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public byte RequestTypeId { get; set; }
        public int UserId { get; set; }
        public string RecurringRequestToken { get; set; }
        public string TrackingID { get; set; }
        public string TransactionId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.Guid> InstrumentId { get; set; }
        public Nullable<System.Guid> SourceRequestId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public Nullable<int> PriceLineId { get; set; }
    
        public virtual USER_Addresses USER_Addresses { get; set; }
        public virtual USER_PaymentInstruments USER_PaymentInstruments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYPAL_PaymentRequests> PAYPAL_PaymentRequests1 { get; set; }
        public virtual PAYPAL_PaymentRequests PAYPAL_PaymentRequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Transactions> SALE_Transactions { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
