//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class PO_MonthlyPayoutToken
    {
        public Nullable<int> UserId { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public string PaypalEmail { get; set; }
        public Nullable<int> PayoutAddressID { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<short> StateId { get; set; }
        public string StateName { get; set; }
        public string PayoutFirstName { get; set; }
        public string PayoutLastName { get; set; }
        public string CityName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public short CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string Symbol { get; set; }
        public string ISO { get; set; }
        public decimal TotalSales { get; set; }
        public decimal AuthorSales { get; set; }
        public decimal AffiliateTotalSales { get; set; }
        public decimal AffiliateFees { get; set; }
        public decimal AffiliateCommission { get; set; }
        public decimal TotalFees { get; set; }
        public decimal RefundProgramHold { get; set; }
        public decimal RefundProgramReleased { get; set; }
        public decimal TotalRefunded { get; set; }
        public decimal TotalRefundedFees { get; set; }
        public decimal Balance { get; set; }
        public decimal LfeCommissions { get; set; }
        public decimal Payout { get; set; }
        public decimal Author_total_sales { get; set; }
        public decimal Author_total_rgp_sales { get; set; }
        public decimal Author_total_non_rgp_sales { get; set; }
        public decimal Author_total_fees { get; set; }
        public decimal Author_total_rgp_fee { get; set; }
        public decimal Author_total_non_rgp_fee { get; set; }
        public decimal By_Affiliate_total_sales { get; set; }
        public decimal By_Affiliate_total_rgp_sales { get; set; }
        public decimal By_Affiliate_total_non_rgp_sales { get; set; }
        public decimal By_Affiliate_total_fees { get; set; }
        public decimal By_Affiliate_total_rgp_fee { get; set; }
        public decimal By_Affiliate_total_non_rgp_fee { get; set; }
        public decimal By_Affiliate_total_net_rgp_sales { get; set; }
        public decimal By_Affiliate_total_net_non_rgp_sales { get; set; }
        public decimal By_Affiliate_total_net_fees { get; set; }
        public decimal By_Affiliate_total_net_rgp_fee { get; set; }
        public decimal By_Affiliate_total_net_non_rgp_fee { get; set; }
        public decimal Affiliate_total_sales { get; set; }
        public decimal Affiliate_total_rgp_sales { get; set; }
        public decimal Affiliate_total_non_rgp_sales { get; set; }
        public decimal Affiliate_total_commission { get; set; }
        public decimal Affiliate_total_rgp_commission { get; set; }
        public decimal Affiliate_total_non_rgp_commission { get; set; }
        public decimal Affiliate_total_fees { get; set; }
        public decimal Affiliate_total_rgp_fee { get; set; }
        public decimal Affiliate_total_non_rgp_fee { get; set; }
        public decimal Affiliate_total_net_fees { get; set; }
        public decimal Affiliate_total_net_rgp_fee { get; set; }
        public decimal Affiliate_total_net_non_rgp_fee { get; set; }
        public decimal Author_Released_total_rgp_sales { get; set; }
        public decimal Author_Released_total_rgp_fee { get; set; }
        public decimal Affiliate_Released_total_net_rgp_sales { get; set; }
        public decimal Affiliate_Released_total_net_rgp_fee { get; set; }
        public decimal By_Affiliate_Released_total_rgp_commission { get; set; }
        public decimal By_Affiliate_Released_total_net_rgp_fee { get; set; }
        public decimal Author_total_refunded { get; set; }
        public decimal Author_fee_refunded { get; set; }
        public decimal Affiliate_total_refunded { get; set; }
        public decimal Affiliate_fee_refunded { get; set; }
        public decimal Affiliate_total_net_refunded { get; set; }
        public decimal Affiliate_fee_net_refunded { get; set; }
        public decimal By_Affiliate_total_refunded { get; set; }
        public decimal By_Affiliate_fee_refunded { get; set; }
        public decimal By_Affiliate_total_net_refunded { get; set; }
        public decimal By_Affiliate_fee_net_refunded { get; set; }
    }
}
