//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class PO_PayoutExecutionToken
    {
        public int ExecutionId { get; set; }
        public int PayoutYear { get; set; }
        public int PayoutMonth { get; set; }
        public int TotalRows { get; set; }
        public byte StatusId { get; set; }
        public Nullable<int> Id { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string CreatorFirstName { get; set; }
        public string CreatorLastName { get; set; }
        public string UpdatedByFirstName { get; set; }
        public string UpdatedByLastName { get; set; }
        public int TotalCompletedRows { get; set; }
    }
}
