//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class PO_PayoutStatmentToken
    {
        public int ExecutionId { get; set; }
        public byte StatusId { get; set; }
        public Nullable<int> Id { get; set; }
        public int PayoutId { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public decimal Payout { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public string PaypalEmail { get; set; }
        public short CurrencyId { get; set; }
        public string ErrorMessage { get; set; }
        public string CurrencyCode { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string CreatorFirstName { get; set; }
        public string CreatorLastName { get; set; }
        public string UpdatedByFirstName { get; set; }
        public string UpdatedByLastName { get; set; }
        public string LastName { get; set; }
        public string PayKey { get; set; }
    }
}
