//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_UserPayoutStatments
    {
        public int PayoutId { get; set; }
        public int ExecutionId { get; set; }
        public int UserId { get; set; }
        public decimal TotalSales { get; set; }
        public decimal AffiliateSales { get; set; }
        public decimal TotalFees { get; set; }
        public decimal RefundProgramHold { get; set; }
        public decimal RefundProgramReleased { get; set; }
        public decimal AffiliateCommission { get; set; }
        public decimal TotalRefunded { get; set; }
        public decimal TotalRefundedFees { get; set; }
        public decimal TotalBalance { get; set; }
        public decimal LfeCommissions { get; set; }
        public decimal Payout { get; set; }
        public decimal Author_total_sales { get; set; }
        public decimal Author_total_rgp_sales { get; set; }
        public decimal Author_total_non_rgp_sales { get; set; }
        public decimal Author_total_fees { get; set; }
        public decimal Author_total_rgp_fee { get; set; }
        public decimal Author_total_non_rgp_fee { get; set; }
        public decimal By_Affiliate_total_sales { get; set; }
        public decimal By_Affiliate_total_rgp_sales { get; set; }
        public decimal By_Affiliate_total_non_rgp_sales { get; set; }
        public decimal By_Affiliate_total_fees { get; set; }
        public decimal By_Affiliate_total_rgp_fee { get; set; }
        public decimal By_Affiliate_total_non_rgp_fee { get; set; }
        public decimal By_Affiliate_total_net_rgp_sales { get; set; }
        public decimal By_Affiliate_total_net_non_rgp_sales { get; set; }
        public decimal By_Affiliate_total_net_fees { get; set; }
        public decimal By_Affiliate_total_net_rgp_fee { get; set; }
        public decimal By_Affiliate_total_net_non_rgp_fee { get; set; }
        public decimal Affiliate_total_sales { get; set; }
        public decimal Affiliate_total_rgp_sales { get; set; }
        public decimal Affiliate_total_non_rgp_sales { get; set; }
        public decimal Affiliate_total_commission { get; set; }
        public decimal Affiliate_total_rgp_commission { get; set; }
        public decimal Affiliate_total_non_rgp_commission { get; set; }
        public decimal Affiliate_total_fees { get; set; }
        public decimal Affiliate_total_rgp_fee { get; set; }
        public decimal Affiliate_total_non_rgp_fee { get; set; }
        public decimal Affiliate_total_net_fees { get; set; }
        public decimal Affiliate_total_net_rgp_fee { get; set; }
        public decimal Affiliate_total_net_non_rgp_fee { get; set; }
        public decimal Author_Released_total_rgp_sales { get; set; }
        public decimal Author_Released_total_rgp_fee { get; set; }
        public decimal Affiliate_Released_total_net_rgp_sales { get; set; }
        public decimal Affiliate_Released_total_net_rgp_fee { get; set; }
        public decimal By_Affiliate_Released_total_rgp_commission { get; set; }
        public decimal By_Affiliate_Released_total_net_rgp_fee { get; set; }
        public decimal Author_total_refunded { get; set; }
        public decimal Author_fee_refunded { get; set; }
        public decimal Affiliate_total_refunded { get; set; }
        public decimal Affiliate_fee_refunded { get; set; }
        public decimal Affiliate_total_net_refunded { get; set; }
        public decimal Affiliate_fee_net_refunded { get; set; }
        public decimal By_Affiliate_total_refunded { get; set; }
        public decimal By_Affiliate_fee_refunded { get; set; }
        public decimal By_Affiliate_total_net_refunded { get; set; }
        public decimal By_Affiliate_fee_net_refunded { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public string PaypalEmail { get; set; }
        public Nullable<int> PayoutAddressID { get; set; }
        public short CurrencyId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ErrorMessage { get; set; }
        public decimal AuthorSales { get; set; }
        public decimal AffiliateFees { get; set; }
        public string PayKey { get; set; }
        public Nullable<decimal> PaymentFee { get; set; }
    
        public virtual BASE_CurrencyLib BASE_CurrencyLib { get; set; }
        public virtual PO_PayoutExecutions PO_PayoutExecutions { get; set; }
        public virtual Users Users { get; set; }
    }
}
