//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class QZ_CourseQuizToken
    {
        public System.Guid QuizId { get; set; }
        public string Title { get; set; }
        public byte StatusId { get; set; }
        public Nullable<byte> PassPercent { get; set; }
        public int CourseId { get; set; }
        public Nullable<short> AvailableAfter { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<byte> Attempts { get; set; }
        public Nullable<short> TimeLimit { get; set; }
        public System.DateTime AddOn { get; set; }
        public bool IsBackAllowed { get; set; }
        public int Sid { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public bool RandomOrder { get; set; }
        public int TotalCompleted { get; set; }
        public int TotalTaken { get; set; }
        public int TotalQustions { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public byte ScoreRuleId { get; set; }
        public bool AttachCertificate { get; set; }
    }
}
