//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZ_CourseQuizzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QZ_CourseQuizzes()
        {
            this.QZ_QuizQuestionsLib = new HashSet<QZ_QuizQuestionsLib>();
            this.QZ_StudentQuizzes = new HashSet<QZ_StudentQuizzes>();
        }
    
        public System.Guid QuizId { get; set; }
        public int Sid { get; set; }
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public Nullable<byte> PassPercent { get; set; }
        public byte ScoreRuleId { get; set; }
        public bool RandomOrder { get; set; }
        public Nullable<short> AvailableAfter { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsBackAllowed { get; set; }
        public Nullable<byte> Attempts { get; set; }
        public Nullable<short> TimeLimit { get; set; }
        public bool IsAttached { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool AttachCertificate { get; set; }
    
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QZ_QuizQuestionsLib> QZ_QuizQuestionsLib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QZ_StudentQuizzes> QZ_StudentQuizzes { get; set; }
    }
}
