//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZ_QuizQuestionsLib
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QZ_QuizQuestionsLib()
        {
            this.QZ_QuestionAnswerOptions = new HashSet<QZ_QuestionAnswerOptions>();
        }
    
        public int QuestionId { get; set; }
        public System.Guid QuizId { get; set; }
        public byte TypeId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<byte> Score { get; set; }
        public string Description { get; set; }
        public Nullable<long> BcIdentifier { get; set; }
        public string ImageUrl { get; set; }
        public short OrderIndex { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QZ_QuestionAnswerOptions> QZ_QuestionAnswerOptions { get; set; }
        public virtual QZ_CourseQuizzes QZ_CourseQuizzes { get; set; }
    }
}
