//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class QZ_QuizBaseToken
    {
        public System.Guid QuizId { get; set; }
        public int Sid { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public byte StatusId { get; set; }
        public Nullable<byte> PassPercent { get; set; }
        public Nullable<int> CertificateId { get; set; }
        public string CertificateName { get; set; }
    }
}
