//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZ_StudentQuizAnswers
    {
        public int AnswerId { get; set; }
        public System.Guid AttemptId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> OptionId { get; set; }
        public string AnswerText { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<byte> Score { get; set; }
        public int OrderIndex { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual QZ_StudentQuizAttempts QZ_StudentQuizAttempts { get; set; }
    }
}
