//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_OrderLinePaymentRefunds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_OrderLinePaymentRefunds()
        {
            this.SALE_Transactions = new HashSet<SALE_Transactions>();
            this.SALE_RefundRequests = new HashSet<SALE_RefundRequests>();
        }
    
        public int RefundId { get; set; }
        public int PaymentId { get; set; }
        public byte TypeId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime RefundDate { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Transactions> SALE_Transactions { get; set; }
        public virtual SALE_OrderLinePayments SALE_OrderLinePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_RefundRequests> SALE_RefundRequests { get; set; }
    }
}
