//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class SALE_SalesStatisticToken
    {
        public Nullable<int> TotalTrx { get; set; }
        public Nullable<int> TotalLearner { get; set; }
        public decimal TotalTrxAmount { get; set; }
    }
}
