//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_RefundRequests
    {
        public int RequestId { get; set; }
        public System.Guid ReferenceKey { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> RefundId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> AuthorResponseOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string Error { get; set; }
    
        public virtual SALE_OrderLinePaymentRefunds SALE_OrderLinePaymentRefunds { get; set; }
        public virtual SALE_OrderLinePayments SALE_OrderLinePayments { get; set; }
    }
}
