//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_OrderLines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_OrderLines()
        {
            this.SALE_Transactions = new HashSet<SALE_Transactions>();
            this.SALE_OrderLinePayments = new HashSet<SALE_OrderLinePayments>();
            this.USER_Bundles = new HashSet<USER_Bundles>();
            this.USER_Courses = new HashSet<USER_Courses>();
        }
    
        public int LineId { get; set; }
        public System.Guid OrderId { get; set; }
        public byte LineTypeId { get; set; }
        public byte PaymentTermId { get; set; }
        public string ItemName { get; set; }
        public int SellerUserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public Nullable<int> CouponInstanceId { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal Fee { get; set; }
        public decimal TotalPrice { get; set; }
        public string PaypalProfileID { get; set; }
        public string Description { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> PriceLineId { get; set; }
        public bool IsUnderRGP { get; set; }
        public Nullable<decimal> AffiliateCommission { get; set; }
    
        public virtual SALE_Orders SALE_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Transactions> SALE_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_OrderLinePayments> SALE_OrderLinePayments { get; set; }
        public virtual CouponInstances CouponInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Bundles> USER_Bundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Courses> USER_Courses { get; set; }
        public virtual BILL_ItemsPriceList BILL_ItemsPriceList { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
