//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_OrderLinePayments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_OrderLinePayments()
        {
            this.SALE_OrderLinePaymentRefunds = new HashSet<SALE_OrderLinePaymentRefunds>();
            this.SALE_Transactions = new HashSet<SALE_Transactions>();
            this.SALE_RefundRequests = new HashSet<SALE_RefundRequests>();
        }
    
        public int PaymentId { get; set; }
        public int OrderLineId { get; set; }
        public byte TypeId { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public short PaymentNumber { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_OrderLinePaymentRefunds> SALE_OrderLinePaymentRefunds { get; set; }
        public virtual SALE_OrderLines SALE_OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Transactions> SALE_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_RefundRequests> SALE_RefundRequests { get; set; }
    }
}
