//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserNotifications()
        {
            this.EMAIL_Messages = new HashSet<EMAIL_Messages>();
            this.FB_PostInterface = new HashSet<FB_PostInterface>();
        }
    
        public long NotificationId { get; set; }
        public int UserId { get; set; }
        public Nullable<long> MessageId { get; set; }
        public bool IsRead { get; set; }
        public bool EmailRequired { get; set; }
        public Nullable<System.DateTime> EmailSendOn { get; set; }
        public bool FbPostRequired { get; set; }
        public Nullable<System.DateTime> FbPostSendOn { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> ReadOn { get; set; }
    
        public virtual DSC_Messages DSC_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_Messages> EMAIL_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_PostInterface> FB_PostInterface { get; set; }
        public virtual Users Users { get; set; }
    }
}
