//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PaymentInstruments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_PaymentInstruments()
        {
            this.PAYPAL_PaymentRequests = new HashSet<PAYPAL_PaymentRequests>();
            this.SALE_Orders = new HashSet<SALE_Orders>();
        }
    
        public System.Guid InstrumentId { get; set; }
        public int UserId { get; set; }
        public byte PaymentMethodId { get; set; }
        public string PaypalCcToken { get; set; }
        public string PaypalAgreementToken { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string DisplayName { get; set; }
        public string CreditCardType { get; set; }
        public int AddressId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYPAL_PaymentRequests> PAYPAL_PaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Orders> SALE_Orders { get; set; }
        public virtual USER_Addresses USER_Addresses { get; set; }
        public virtual Users Users { get; set; }
    }
}
