//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class USER_VideoInfoToken
    {
        public int VideoId { get; set; }
        public int UserId { get; set; }
        public long BcIdentifier { get; set; }
        public string Name { get; set; }
        public string ThumbUrl { get; set; }
        public string Duration { get; set; }
        public bool Attached2Chapter { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
