//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_Bundles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_Bundles()
        {
            this.USER_Courses = new HashSet<USER_Courses>();
        }
    
        public int UserBundleId { get; set; }
        public int OrderLineId { get; set; }
        public int UserId { get; set; }
        public int BundleId { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual SALE_OrderLines SALE_OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Courses> USER_Courses { get; set; }
        public virtual CRS_Bundles CRS_Bundles { get; set; }
        public virtual Users Users { get; set; }
    }
}
