//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class USER_ReviewToken
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int AuthorId { get; set; }
        public int ReviewId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> ReviewRating { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewText { get; set; }
        public int LearnerId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
