//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.APP_PluginInstallations = new HashSet<APP_PluginInstallations>();
            this.CHIMP_UserLists = new HashSet<CHIMP_UserLists>();
            this.Coupons = new HashSet<Coupons>();
            this.CRS_Bundles = new HashSet<CRS_Bundles>();
            this.DSC_Followers = new HashSet<DSC_Followers>();
            this.DSC_Followers1 = new HashSet<DSC_Followers>();
            this.DSC_Hashtags = new HashSet<DSC_Hashtags>();
            this.DSC_MessageUsers = new HashSet<DSC_MessageUsers>();
            this.EMAIL_Messages = new HashSet<EMAIL_Messages>();
            this.FACT_EventAgg = new HashSet<FACT_EventAgg>();
            this.FB_PostInterface = new HashSet<FB_PostInterface>();
            this.PAYPAL_PaymentRequests = new HashSet<PAYPAL_PaymentRequests>();
            this.SALE_OrderLines = new HashSet<SALE_OrderLines>();
            this.SALE_Orders = new HashSet<SALE_Orders>();
            this.SALE_Orders1 = new HashSet<SALE_Orders>();
            this.USER_Addresses = new HashSet<USER_Addresses>();
            this.USER_Bundles = new HashSet<USER_Bundles>();
            this.USER_Courses = new HashSet<USER_Courses>();
            this.USER_CourseWatchState = new HashSet<USER_CourseWatchState>();
            this.USER_Logins = new HashSet<USER_Logins>();
            this.USER_PaymentInstruments = new HashSet<USER_PaymentInstruments>();
            this.USER_Videos = new HashSet<USER_Videos>();
            this.UserCourseReviews = new HashSet<UserCourseReviews>();
            this.UserNotifications = new HashSet<UserNotifications>();
            this.UserProfile = new HashSet<UserProfile>();
            this.UserS3FileInterface = new HashSet<UserS3FileInterface>();
            this.UserSessions = new HashSet<UserSessions>();
            this.WebStores1 = new HashSet<WebStores>();
            this.ApiSessions = new HashSet<ApiSessions>();
            this.USER_RefundProgramRevisions = new HashSet<USER_RefundProgramRevisions>();
            this.PO_UserPayoutStatments = new HashSet<PO_UserPayoutStatments>();
            this.DB_CustomEvents = new HashSet<DB_CustomEvents>();
            this.Courses = new HashSet<Courses>();
            this.USER_VideoStats = new HashSet<USER_VideoStats>();
            this.QZ_StudentQuizzes = new HashSet<QZ_StudentQuizzes>();
            this.CERT_StudentCertificates = new HashSet<CERT_StudentCertificates>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ActivationToken { get; set; }
        public Nullable<System.DateTime> ActivationExpiration { get; set; }
        public string FacebookID { get; set; }
        public int StatusType { get; set; }
        public decimal AffiliateCommission { get; set; }
        public string PasswordDigest { get; set; }
        public string PictureURL { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string BioHtml { get; set; }
        public string AuthorPictureURL { get; set; }
        public bool AutoplayEnabled { get; set; }
        public int UserTypeID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string salesforce_id { get; set; }
        public string salesforce_checksum { get; set; }
        public bool DisplayActivitiesOnFB { get; set; }
        public bool ReceiveMonthlyNewsletterOnEmail { get; set; }
        public bool DisplayDiscussionFeedDailyOnFB { get; set; }
        public bool ReceiveDiscussionFeedDailyOnEmail { get; set; }
        public bool DisplayCourseNewsWeeklyOnFB { get; set; }
        public bool ReceiveCourseNewsWeeklyOnEmail { get; set; }
        public byte RegistrationTypeId { get; set; }
        public Nullable<int> RegisterStoreId { get; set; }
        public string RegisterHostName { get; set; }
        public string FbAccessToken { get; set; }
        public Nullable<System.DateTime> FbAccessTokenExpired { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public Nullable<int> PayoutAddressID { get; set; }
        public string PaypalEmail { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool JoinedToRefundProgram { get; set; }
        public Nullable<System.Guid> ProvisionUid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_PluginInstallations> APP_PluginInstallations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIMP_UserLists> CHIMP_UserLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupons> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRS_Bundles> CRS_Bundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Followers> DSC_Followers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Followers> DSC_Followers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_Hashtags> DSC_Hashtags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSC_MessageUsers> DSC_MessageUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_Messages> EMAIL_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACT_EventAgg> FACT_EventAgg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_PostInterface> FB_PostInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYPAL_PaymentRequests> PAYPAL_PaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_OrderLines> SALE_OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Orders> SALE_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Orders> SALE_Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Addresses> USER_Addresses { get; set; }
        public virtual USER_Addresses USER_Addresses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Bundles> USER_Bundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Courses> USER_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_CourseWatchState> USER_CourseWatchState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Logins> USER_Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PaymentInstruments> USER_PaymentInstruments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_Videos> USER_Videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCourseReviews> UserCourseReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotifications> UserNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual WebStores WebStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserS3FileInterface> UserS3FileInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSessions> UserSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStores> WebStores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiSessions> ApiSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_RefundProgramRevisions> USER_RefundProgramRevisions { get; set; }
        public virtual UserStatusTypes UserStatusTypes { get; set; }
        public virtual UserTypes UserTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_UserPayoutStatments> PO_UserPayoutStatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_CustomEvents> DB_CustomEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_VideoStats> USER_VideoStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QZ_StudentQuizzes> QZ_StudentQuizzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERT_StudentCertificates> CERT_StudentCertificates { get; set; }
    }
}
