//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class USER_BillingAddressToken
    {
        public int AddressId { get; set; }
        public int UserId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string CountryName { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public Nullable<short> StateId { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CityName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string PostalCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Region { get; set; }
        public string Description { get; set; }
    }
}
