//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSessions()
        {
            this.UserSessionsEventLogs = new HashSet<UserSessionsEventLogs>();
        }
    
        public long SessionId { get; set; }
        public string NetSessionId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
        public string HostName { get; set; }
        public string HttpHeaders { get; set; }
        public string salesforce_id { get; set; }
        public string salesforce_checksum { get; set; }
        public System.DateTime EventDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSessionsEventLogs> UserSessionsEventLogs { get; set; }
        public virtual Users Users { get; set; }
    }
}
