//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class USER_MonthlyStatementToken
    {
        public decimal total { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string PaymentSource { get; set; }
        public int SellerUserId { get; set; }
    }
}
