//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_Videos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_Videos()
        {
            this.USER_VideosRenditions = new HashSet<USER_VideosRenditions>();
        }
    
        public int VideoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public long BcIdentifier { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Attached2Chapter { get; set; }
        public string ThumbUrl { get; set; }
        public string Duration { get; set; }
        public string ShortDescription { get; set; }
        public string ReferenceId { get; set; }
        public string VideoStillUrl { get; set; }
        public string Tags { get; set; }
        public int PlaysTotal { get; set; }
        public long Length { get; set; }
        public string S3Url { get; set; }
        public string PlaylistUrl { get; set; }
        public Nullable<System.DateTime> LastTranscodeDate { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_VideosRenditions> USER_VideosRenditions { get; set; }
    }
}
