//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_VideosRenditions
    {
        public long RenditionId { get; set; }
        public int VideoId { get; set; }
        public string Location { get; set; }
        public string S3Url { get; set; }
        public string CloudFrontPath { get; set; }
        public bool AudioOnly { get; set; }
        public string ControllerType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> EncodingRate { get; set; }
        public Nullable<int> FrameHeight { get; set; }
        public Nullable<int> FrameWidth { get; set; }
        public string ReferenceId { get; set; }
        public string RemoteStreamName { get; set; }
        public string RemoteUrl { get; set; }
        public Nullable<long> Size { get; set; }
        public Nullable<long> UploadTimestampMillis { get; set; }
        public string Url { get; set; }
        public string VideoCodec { get; set; }
        public string VideoContainer { get; set; }
        public Nullable<long> VideoDuration { get; set; }
        public bool CreatedInS3 { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> S3Size { get; set; }
    
        public virtual USER_Videos USER_Videos { get; set; }
        public virtual USER_VideosRenditions USER_VideosRenditions1 { get; set; }
        public virtual USER_VideosRenditions USER_VideosRenditions2 { get; set; }
    }
}
