//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class USER_NotificationToken
    {
        public long MessageId { get; set; }
        public int ClassRoomId { get; set; }
        public string RoomName { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseUrlName { get; set; }
        public short MessageKindId { get; set; }
        public string Text { get; set; }
        public string HtmlMessage { get; set; }
        public int UserId { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureURL { get; set; }
        public System.DateTime AddOn { get; set; }
        public bool IsRead { get; set; }
        public System.Guid Uid { get; set; }
        public string FacebookID { get; set; }
    }
}
