//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_Logins
    {
        public long LoginId { get; set; }
        public int UserId { get; set; }
        public string NetSessionId { get; set; }
        public string HostName { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<System.DateTime> SignOutDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
