//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourseReviews
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> ReviewRating { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewText { get; set; }
        public bool Approved { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
