//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CERT_StudentCertificates
    {
        public System.Guid StudentCertificateId { get; set; }
        public int StudentUserId { get; set; }
        public string StudentEmail { get; set; }
        public string StudentNickname { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public int CertificateId { get; set; }
        public byte TemplateId { get; set; }
        public string Title { get; set; }
        public string CourseName { get; set; }
        public string SitgnatureUrl { get; set; }
        public string PresentedBy { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public int AuthorUserId { get; set; }
        public string AuthorEmail { get; set; }
        public string AuthorNickname { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public int CourseId { get; set; }
        public string TemplateImageName { get; set; }
        public System.DateTime AddOn { get; set; }
    }
}
