//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EVENT_Logs
    {
        public long EventID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short EventTypeID { get; set; }
        public string TypeCode { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> BundleId { get; set; }
        public string BundleName { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> BundleAuthorId { get; set; }
        public Nullable<int> CourseAuthorId { get; set; }
        public string AdditionalData { get; set; }
        public string AubsoluteUri { get; set; }
        public long SessionId { get; set; }
        public bool ExportToFact { get; set; }
        public Nullable<int> StoreOwnerUserID { get; set; }
    }
}
