//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FACT_EventAggregates
    {
        public int EventCount { get; set; }
        public short EventTypeID { get; set; }
        public string TypeCode { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string ItemName { get; set; }
        public string StoreName { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
