//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QZ_QuizQuestionsLib
    {
        public int QuestionId { get; set; }
        public System.Guid QuizId { get; set; }
        public int QuizSid { get; set; }
        public byte TypeId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<byte> Score { get; set; }
        public string Description { get; set; }
        public Nullable<long> BcIdentifier { get; set; }
        public string ImageUrl { get; set; }
        public short OrderIndex { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddOn { get; set; }
        public int TotalAnswers { get; set; }
        public int CorrectAnswer { get; set; }
    }
}
