//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QZ_CourseQuizzes
    {
        public System.Guid QuizId { get; set; }
        public int Sid { get; set; }
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public Nullable<byte> PassPercent { get; set; }
        public bool RandomOrder { get; set; }
        public byte StatusId { get; set; }
        public System.DateTime AddOn { get; set; }
        public int TotalCompleted { get; set; }
        public int TotalTaken { get; set; }
        public int TotalQustions { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public byte ScoreRuleId { get; set; }
        public Nullable<short> AvailableAfter { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsBackAllowed { get; set; }
        public Nullable<byte> Attempts { get; set; }
        public Nullable<short> TimeLimit { get; set; }
        public bool IsAttached { get; set; }
        public bool AttachCertificate { get; set; }
        public int AuthorUserId { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CourseName { get; set; }
        public int OpenRequests { get; set; }
        public int TotalPass { get; set; }
        public int TotalFailed { get; set; }
    }
}
