//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SALE_Orders
    {
        public System.Guid OrderId { get; set; }
        public int Sid { get; set; }
        public decimal TotalAmount { get; set; }
        public int BuyerUserId { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerNickName { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public int SellerUserId { get; set; }
        public string SellerEmail { get; set; }
        public string SellerNickName { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public byte StatusId { get; set; }
        public string StatusCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> AddressId { get; set; }
        public byte PaymentMethodId { get; set; }
        public string PaymentMethodCode { get; set; }
        public Nullable<System.Guid> InstrumentId { get; set; }
        public string CreditCardType { get; set; }
        public string DisplayName { get; set; }
        public string ISO { get; set; }
        public Nullable<int> StoreOwnerUserId { get; set; }
        public decimal AffiliateCommission { get; set; }
    }
}
