//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SALE_OrderLines
    {
        public System.Guid OrderId { get; set; }
        public int LineId { get; set; }
        public int OrderNumber { get; set; }
        public int SellerUserId { get; set; }
        public string SellerEmail { get; set; }
        public string SellerNickName { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public int BuyerUserId { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerNickName { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public string OrderStatusCode { get; set; }
        public byte OrderStatusId { get; set; }
        public byte PaymentMethodId { get; set; }
        public string PaymentMethodCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public byte LineTypeId { get; set; }
        public string LineTypeCode { get; set; }
        public byte PaymentTermId { get; set; }
        public string PaymentTermCode { get; set; }
        public string ItemName { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalAmountPayed { get; set; }
        public string PaypalProfileID { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoreOwnerUserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public decimal TotalRefunded { get; set; }
        public Nullable<int> CouponInstanceId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<double> CouponTypeAmount { get; set; }
        public Nullable<byte> CouponTypeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.Guid> InstrumentId { get; set; }
        public string CreditCardType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> PriceLineId { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public string CurrencyName { get; set; }
        public string SellerFacebookID { get; set; }
        public string BuyerFacebookID { get; set; }
        public bool IsUnderRGP { get; set; }
        public Nullable<decimal> AffiliateCommission { get; set; }
        public string StoreOwnerEmail { get; set; }
        public string StoreOwnerNickname { get; set; }
        public string StoreOwnerFirstName { get; set; }
        public string StoreOwnerLastName { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
    }
}
