//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SALE_OrderLinePayments
    {
        public int PaymentId { get; set; }
        public int OrderLineId { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public short PaymentNumber { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string StatusCode { get; set; }
        public decimal TotalRefunded { get; set; }
        public byte LineTypeId { get; set; }
        public string TypeCode { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string ExternalTransactionID { get; set; }
        public string PaypalProfileID { get; set; }
        public byte PaymentTypeId { get; set; }
        public string PaymentTypeCode { get; set; }
        public System.Guid OrderId { get; set; }
        public string ItemName { get; set; }
        public int OrderNumber { get; set; }
        public int BuyerUserId { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerNickName { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public int SellerUserId { get; set; }
        public string SellerEmail { get; set; }
        public string SellerNickName { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public byte OrderStatusId { get; set; }
        public string OrderStatusCode { get; set; }
        public byte PaymentMethodId { get; set; }
        public Nullable<System.Guid> InstrumentId { get; set; }
        public string CreditCardType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public string PaymentMethodCode { get; set; }
        public Nullable<int> CouponInstanceId { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal Discount { get; set; }
        public Nullable<byte> SubscriptionMonths { get; set; }
        public Nullable<double> CouponTypeAmount { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> PriceLineId { get; set; }
        public short CurrencyId { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public string CurrencyName { get; set; }
        public decimal AffiliateCommission { get; set; }
        public bool IsUnderRGP { get; set; }
        public Nullable<int> StoreOwnerUserId { get; set; }
        public string StoreOwnerEmail { get; set; }
        public string StoreOwnerNickname { get; set; }
        public string StoreOwnerFirstName { get; set; }
        public string StoreOwnerLastName { get; set; }
        public Nullable<byte> CouponTypeId { get; set; }
    }
}
