//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SALE_Transactions
    {
        public int TransactionId { get; set; }
        public int OrderNumber { get; set; }
        public System.Guid OrderId { get; set; }
        public int BuyerUserId { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerNickName { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public byte PaymentMethodId { get; set; }
        public string PaymentMethodCode { get; set; }
        public Nullable<System.Guid> InstrumentId { get; set; }
        public string PaymentIntsrumentDisplayName { get; set; }
        public int LineId { get; set; }
        public byte LineTypeId { get; set; }
        public string LineTypeCode { get; set; }
        public byte PaymentTermId { get; set; }
        public string PaymentTermCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BundleId { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<short> PaymentNumber { get; set; }
        public Nullable<byte> PaymentStatusId { get; set; }
        public string PaymentStatusCode { get; set; }
        public byte TransactionTypeId { get; set; }
        public string TransactionTypeCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ExternalTransactionID { get; set; }
        public decimal Amount { get; set; }
        public decimal Fee { get; set; }
        public string Remarks { get; set; }
        public int SellerUserId { get; set; }
        public string SellerEmail { get; set; }
        public string SellerNickName { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public string CourseName { get; set; }
        public string BundleName { get; set; }
        public Nullable<int> PriceLineId { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string ISO { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.Guid> RequestId { get; set; }
        public Nullable<int> PaymentId { get; set; }
    }
}
