//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_USER_Items
    {
        public int UserItemId { get; set; }
        public byte ItemTypeId { get; set; }
        public int OrderLineId { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public byte AccessStatusId { get; set; }
        public System.Guid uid { get; set; }
        public string ItemName { get; set; }
        public string ItemUrlName { get; set; }
        public string ItemDescription { get; set; }
        public int AuthorId { get; set; }
        public string AuthorNickName { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public Nullable<bool> IsFreeCourse { get; set; }
        public string ImageUrl { get; set; }
        public int Rating { get; set; }
        public int NumSubscribers { get; set; }
        public short ItemStatusId { get; set; }
        public Nullable<long> FbObjectId { get; set; }
        public System.DateTime Created { get; set; }
        public int CoursesCnt { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    }
}
