//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_USER_EventsLog
    {
        public long EventID { get; set; }
        public long SessionId { get; set; }
        public string NetSessionId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureURL { get; set; }
        public string IPAddress { get; set; }
        public string HostName { get; set; }
        public string HttpHeaders { get; set; }
        public System.DateTime SessionDate { get; set; }
        public short EventTypeID { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public string AdditionalData { get; set; }
        public System.DateTime EventDate { get; set; }
        public string FacebookID { get; set; }
        public string AubsoluteUri { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseAuthorId { get; set; }
        public string CourseAuthorFirstName { get; set; }
        public string CourseAuthorLastName { get; set; }
        public string CourseAuthorNickname { get; set; }
        public Nullable<int> BundleId { get; set; }
        public string BundleName { get; set; }
        public Nullable<int> BundleAuthorId { get; set; }
        public string BundleAuthorFirstName { get; set; }
        public string BundleAuthorLastName { get; set; }
        public string BundleAuthorNickname { get; set; }
        public Nullable<int> WebStoreId { get; set; }
        public string StoreName { get; set; }
        public string TrackingID { get; set; }
        public string WixSiteUrl { get; set; }
        public Nullable<int> StoreOwnerUserID { get; set; }
        public string StoreOwnerNickname { get; set; }
        public string StoreOwnerFirstName { get; set; }
        public string StoreOwnerLastName { get; set; }
        public Nullable<long> VideoBcIdentifier { get; set; }
        public string VideoName { get; set; }
        public string VideoDuration { get; set; }
        public string VideoThumbUrl { get; set; }
        public Nullable<int> VideoAuthorId { get; set; }
        public string VideoAuthorFirstName { get; set; }
        public string VideoAuthorLastName { get; set; }
        public string VideoAuthorNickname { get; set; }
    }
}
