//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_USER_UserLogins
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FacebookID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public bool IsConfirmed { get; set; }
        public string ProviderUserId { get; set; }
        public string Provider { get; set; }
        public string Email { get; set; }
        public string PictureURL { get; set; }
        public string AuthorPictureURL { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int StatusType { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public byte RegistrationTypeId { get; set; }
        public string RegistrationTypeCode { get; set; }
        public int courses { get; set; }
        public int bundles { get; set; }
        public int chapters { get; set; }
        public int videos { get; set; }
        public int logins { get; set; }
        public int purchases { get; set; }
        public int stores { get; set; }
        public Nullable<int> RegisterStoreId { get; set; }
        public string RegisterStoreName { get; set; }
        public Nullable<byte> PayoutTypeId { get; set; }
        public string PayoutTypeCode { get; set; }
        public Nullable<int> PayoutAddressID { get; set; }
        public string PaypalEmail { get; set; }
        public System.DateTime Created { get; set; }
        public string RegisterHostName { get; set; }
        public bool JoinedToRefundProgram { get; set; }
        public Nullable<System.Guid> ProvisionUid { get; set; }
    }
}
