//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WS_StoresLib
    {
        public int StoreID { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public int OwnerUserID { get; set; }
        public Nullable<bool> IsOwnerAdmin { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerNickname { get; set; }
        public int AffiliateItems { get; set; }
        public int OwnedItems { get; set; }
        public Nullable<short> DefaultCurrencyId { get; set; }
        public Nullable<System.Guid> WixInstanceId { get; set; }
        public Nullable<byte> RegistrationSourceId { get; set; }
        public string RegistrationTypeCode { get; set; }
        public string WixSiteUrl { get; set; }
        public System.Guid uid { get; set; }
        public string SiteUrl { get; set; }
        public System.DateTime AddOn { get; set; }
    }
}
