//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebStoreCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebStoreCategories()
        {
            this.WebStoreItems = new HashSet<WebStoreItems>();
        }
    
        public int WebStoreCategoryID { get; set; }
        public int WebStoreID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryUrlName { get; set; }
        public string Description { get; set; }
        public int Ordinal { get; set; }
        public bool IsPublic { get; set; }
        public bool IsAutoUpdate { get; set; }
        public System.DateTime AddOn { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual WebStores WebStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStoreItems> WebStoreItems { get; set; }
    }
}
