//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebStores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebStores()
        {
            this.WebStoreCategories = new HashSet<WebStoreCategories>();
            this.WebStoresChangeLog = new HashSet<WebStoresChangeLog>();
            this.SALE_Orders = new HashSet<SALE_Orders>();
            this.UserSessionsEventLogs = new HashSet<UserSessionsEventLogs>();
            this.FACT_EventAgg = new HashSet<FACT_EventAgg>();
            this.APP_PluginInstallationStores = new HashSet<APP_PluginInstallationStores>();
            this.Users = new HashSet<Users>();
        }
    
        public int StoreID { get; set; }
        public System.Guid uid { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public string GoogleAnalyticCode { get; set; }
        public string MetaTags { get; set; }
        public string Description { get; set; }
        public short StatusId { get; set; }
        public int OwnerUserID { get; set; }
        public Nullable<System.Guid> WixInstanceId { get; set; }
        public System.DateTime AddOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string BackgroundColor { get; set; }
        public string FontColor { get; set; }
        public string TabsFontColor { get; set; }
        public Nullable<bool> IsShowBorder { get; set; }
        public Nullable<bool> IsShowTitleBar { get; set; }
        public Nullable<bool> IsTransparent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string WixSiteUrl { get; set; }
        public Nullable<short> DefaultCurrencyId { get; set; }
        public Nullable<byte> RegistrationSourceId { get; set; }
        public string SiteUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStoreCategories> WebStoreCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebStoresChangeLog> WebStoresChangeLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_Orders> SALE_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSessionsEventLogs> UserSessionsEventLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACT_EventAgg> FACT_EventAgg { get; set; }
        public virtual BASE_CurrencyLib BASE_CurrencyLib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_PluginInstallationStores> APP_PluginInstallationStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual StatusLOV StatusLOV { get; set; }
    }
}
