//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class WIDGET_CourseListToken
    {
        public string AuthorName { get; set; }
        public int AuthorID { get; set; }
        public string ImageURL { get; set; }
        public int NumSubscribers { get; set; }
        public int Rating { get; set; }
        public Nullable<bool> IsFreeCourse { get; set; }
        public int SumCourses { get; set; }
        public string ItemName { get; set; }
        public byte ItemTypeId { get; set; }
        public int Ordinal { get; set; }
        public int ItemId { get; set; }
        public string UrlName { get; set; }
        public System.DateTime Created { get; set; }
        public int CoursesCnt { get; set; }
    }
}
