//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class WS_AffiliateItemToken
    {
        public int WebstoreItemId { get; set; }
        public string LineType { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemUrlName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MonthlySubscriptionPrice { get; set; }
        public int StoreID { get; set; }
        public string TrackingID { get; set; }
        public string StoreName { get; set; }
        public int OwnerUserID { get; set; }
        public string OwnerNickName { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public int WebStoreCategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryUrlName { get; set; }
        public int AuthorId { get; set; }
        public string AuthorNickName { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
    }
}
