//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFE.Model
{
    using System;
    
    public partial class WS_ItemCandidateToken
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> WebstoreItemId { get; set; }
        public string ItemType { get; set; }
        public short StatusId { get; set; }
    }
}
